### ISSUE TITLE
Non terminating debug mode

### ISSUE THREAD

**Issue by QuantumInformation** [GoogleCloudPlatform/functions-framework-nodejs#84] opened 2019-09-06 13:13 UTC
When Debugging with 
`"debug": "node --inspect node_modules/@google-cloud/functions-framework --target=api",`

and the app throws an error, eg

```
file:///Users/nikos/…/src/invoker.js:389 Unhandled rejection
(anonymous) @ file:///Users/nikos/…/src/invoker.js:389
emit @ events.js:200
EventEmitter.emit @ domain.js:471
processPromiseRejections @ internal/process/promises.js:165
processTicksAndRejections @ internal/process/task_queues.js:90
file:///Users/nikos/…/src/invoker.js:174 Error: Sorry, we cannot connect to Cloud Services without a project
```

Is there a way to keep the process up? ATM I keep having to restart the debug session.

**Comment by grant** [comment] 2019-09-06 14:22
In general, Node processes can be kept alive with packages like [`forever`](https://www.npmjs.com/package/forever).

This looks like it's working as intended.

**Comment by QuantumInformation** [comment] 2019-09-06 16:45
Cool I'll try that out! Gonna vlog about my discoveries soon!

**Comment by QuantumInformation** [comment] 2019-09-06 17:52
Hmm... Tried this but no cigar.
opened an issue https://github.com/foreversd/forever/issues/1038

**Comment by grant** [comment] 2019-09-06 18:32
I don't know the exact issue with the Functions Framework.
It seems like this issue is more of a developer issues with the local setup of this library.

There are a few blogposts about keeping Node processes up. I'm going to close this issue while there's no issue we can solve with the FF.

Feel free to keep commenting. If there's something the FF should do to change this, please comment and I can re-open this issue.

**Closed by grant** 2019-09-06 18:32 UTC
Labels: question
