### ISSUE TITLE
Cloud Events callback doesn't properly send Cloud Events

### ISSUE THREAD

**Issue by mattmoor** [GoogleCloudPlatform/functions-framework-nodejs#235] opened 2020-11-09 23:18 UTC
I have a trivial function:

```
// handle shared the logic for producing the Response event from the Request.
const handle = (data) => {
    return {
	a: Math.floor(data.a / data.b),
	b: data.a % data.b
    }
}

function event(cloudEvent) {
  console.log(`Got event: ${JSON.stringify(cloudEvent, null, 2)}`)
  const newCloudEvent = new CloudEvent({
      type: 'dev.mink.apply.samples.divide',
      source: 'https://github.com/mattmoor/mink-apply-sample/divide',
      time: new Date(),
      dataContentType: 'application/json',
      data: handle(cloudEvent.data)
  })

  console.log(`Returning event: ${JSON.stringify(newCloudEvent.format(), null, 2)}`)
  return newCloudEvent
}
```

In the logs I see:
```
Got event: {
  "id": "2f835992-25a2-4084-b582-2cff75f2859b",
  "knativearrivaltime": "2020-11-09T20:51:00.193484373Z",
  "source": "/apis/v1/namespaces/default/pingsources/test-ping-source",
  "specversion": "1.0",
  "time": "2020-11-09T20:51:00.191970229Z",
  "type": "dev.knative.sources.ping",
  "data": {
    "a": 11,
    "b": 3
  }
}
Returning event: {
  "data": {
    "a": 3,
    "b": 2
  },
  "specversion": "1.0",
  "id": "3edc8093-c18c-42ce-bcde-ebb835f9b708",
  "time": "2020-11-09T20:51:00.215Z",
  "source": "https://github.com/mattmoor/mink-apply-sample/divide",
  "type": "dev.mink.apply.samples.divide",
  "datacontenttype": "application/json"
}
```

However, the returned event doesn't get properly returned as a cloud event:
```
curl -v -X POST -H 'Content-Type: application/json' -H 'ce-type: foo' -H 'ce-specversion: 1.0' -H 'ce-source: blah' -H 'ce-id: 1234' -d '{"a": 3, "b": 4}' http://divide.default.svc.cluster.local | jq .
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: http://divide.default.svc.cluster.local/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.0.28.2...
* TCP_NODELAY set
* Connected to divide.default.svc.cluster.local (10.0.28.2) port 80 (#0)
> POST / HTTP/1.1
> Host: divide.default.svc.cluster.local
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json
> ce-type: foo
> ce-specversion: 1.0
> ce-source: blah
> ce-id: 1234
> Content-Length: 16
> 
} [16 bytes data]
* upload completely sent off: 16 out of 16 bytes
< HTTP/1.1 200 OK
< content-length: 312
< content-type: application/json; charset=utf-8
< date: Mon, 09 Nov 2020 20:56:02 GMT
< etag: W/"138-pznfqQ6k5rUm3LHClNlYXVHInNQ"
< x-powered-by: Express
< x-envoy-upstream-service-time: 11
< vary: Accept-Encoding
< server: envoy
< 
{ [312 bytes data]
100   328  100   312  100    16   2260    115 --:--:-- --:--:-- --:--:--  2376
* Connection #0 to host divide.default.svc.cluster.local left intact
{
  "spec": {
    "payload": {
      "specversion": "1.0",
      "id": "14d3a7fb-9331-4e99-90d4-738661c4f66e",
      "time": "2020-11-09T20:56:02.558Z",
      "source": "https://github.com/mattmoor/mink-apply-sample/divide",
      "type": "dev.mink.apply.samples.divide",
      "datacontenttype": "application/json",
      "data": {
        "a": 0,
        "b": 3
      }
    }
  },
  "formatter": {},
  "extensions": []
}
```

This is neither a "structured" or a "binary" cloud event!

If I change the final return to:
```
  return newCloudEvent.format()
```

Then the returned body is a proper structured cloud event, with the wrong MIME type:

```
 curl -v -X POST -H 'Content-Type: application/json' -H 'ce-type: foo' -H 'ce-specversion: 1.0' -H 'ce-source: blah' -H 'ce-id: 1234' -d '{"a": 3, "b": 4}' http://divide.default.svc.cluster.local | jq .
Note: Unnecessary use of -X or --request, POST is already inferred.
* Rebuilt URL to: http://divide.default.svc.cluster.local/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.0.28.2...
* TCP_NODELAY set
* Connected to divide.default.svc.cluster.local (10.0.28.2) port 80 (#0)
> POST / HTTP/1.1
> Host: divide.default.svc.cluster.local
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json
> ce-type: foo
> ce-specversion: 1.0
> ce-source: blah
> ce-id: 1234
> Content-Length: 16
> 
} [16 bytes data]
* upload completely sent off: 16 out of 16 bytes
< HTTP/1.1 200 OK
< content-length: 260
< content-type: application/json; charset=utf-8
< date: Mon, 09 Nov 2020 23:16:25 GMT
< etag: W/"104-lrVLt0nXAUiMN4jcclhUw2w+YZg"
< x-powered-by: Express
< x-envoy-upstream-service-time: 38
< vary: Accept-Encoding
< server: envoy
< 
{ [260 bytes data]
100   276  100   260  100    16   1566     96 --:--:-- --:--:-- --:--:--  1652
* Connection #0 to host divide.default.svc.cluster.local left intact
{
  "data": {
    "a": 0,
    "b": 3
  },
  "specversion": "1.0",
  "id": "7fcf9988-cd77-4fbb-af85-6c5bc2a25c3f",
  "time": "2020-11-09T23:16:25.415Z",
  "source": "https://github.com/mattmoor/mink-apply-sample/divide",
  "type": "dev.mink.apply.samples.divide",
  "datacontenttype": "application/json"
}
```

In the above the `Content-Type` header in the response should be `application/cloudevent+json`.  OR it should return the body:
```
{
  "a": 0,
  "b": 3
}
```

... and return the remaining headers via their respective `ce-`prefixed equivalents (e.g. `ce-type: dev.mink.apply.samples.divide`).

**Comment by mattmoor** [comment] 2020-11-09 23:23
cc @grant 

I spent some time debugging the issue I mentioned earlier in email about the implicit `callback` call not WAI.  I'm fairly certain this same issue would imply to the explicitly passed callback case as well, so even with the fix in https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/234 cloud events passed to the callback won't be properly returned to the caller.

**Comment by mattmoor** [comment] 2020-11-09 23:31
cc @n3wscott to sanity check my "math" from a CloudEvents perspective.

**Comment by grant** [comment] 2020-11-10 00:08
Thanks for the issue @mattmoor.

Can you provide **more specific** repro steps? For example:
- It looks like the sample requires some modules (like `cloudevents`)? Did you install anything?
  - Describe the exact steps needed to produce the output
- How are you starting the FF? This is important. What's the full npx command / package.json?

This module doesn't send CloudEvents. Your function just [receives](https://github.com/GoogleCloudPlatform/functions-framework-nodejs#enable-cloudevents) a CloudEvent. Are you expecting that the return value of the function be an object that is sent to some location? Why can't we just POST to that location within the function?

Related: https://github.com/GoogleCloudPlatform/functions-framework/issues/30#issuecomment-718939126

**Comment by mattmoor** [comment] 2020-11-10 00:45
I am using https://github.com/GoogleCloudPlatform/buildpacks to orchestrate all of this, the image URI for the builder image is `gcr.io/buildpacks/builder`.

Virtually the entire skeleton of the function (e.g. `package.json`) was adapted from this Knative sample: https://github.com/knative/docs/tree/release-0.18/docs/serving/samples/cloudevents/cloudevents-nodejs

However, I shed most of the JS to try and adapt it to the function framework, I provided virtually all of this above, this should be the complete bits:
```
const { CloudEvent } = require('cloudevents-sdk')

// handle shared the logic for producing the Response event from the Request.
const handle = (data) => {
    return {
	a: Math.floor(data.a / data.b),
	b: data.a % data.b
    }
}

function event(cloudEvent) {
  const newCloudEvent = new CloudEvent({
      type: 'dev.mink.apply.samples.divide',
      source: 'https://github.com/mattmoor/mink-apply-sample/divide',
      time: new Date(),
      dataContentType: 'application/json',
      data: handle(cloudEvent.data)
  })

  return newCloudEvent
}

// GOOGLE_FUNCTION_TARGET is set to "divide" in project.toml
exports.divide = event
```

Here is the specific version of the cloudevents SDK: https://github.com/knative/docs/blob/29d0c575ac32975caf51289e70fc31cb6f63bde7/docs/serving/samples/cloudevents/cloudevents-nodejs/package.json#L16

This sample describes how to build local source with the buildpack builder image using the above source: https://github.com/GoogleCloudPlatform/buildpack-samples/tree/master/sample-functions-framework-node

**Comment by mattmoor** [comment] 2020-11-10 00:55
> This module doesn't send CloudEvents. Your function just receives a CloudEvent. Are you expecting that the return value of the function be an object that is sent to some location? Why can't we just POST to that location within the function?

The Knative Broker model allows for the recipient of a CloudEvent to reply with a CloudEvent that may be enqueued back onto the Broker.  You are correct, that I am not sending a CloudEvent, I am returning one, which y'all should be replying with via the HTTP response.  This much you *are* doing, you are just replying with the CloudEvent incorrectly (in a few ways).

**Comment by mattmoor** [comment] 2020-11-10 01:03
Effectively on this line, this is naively responding with the cloud event the same way is responds to events:
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/2449956aeef7db4a33e89760ab97ce4a892ff03c/src/invoker.ts#L141

This is basically guaranteed to be wrong in the sense of the Knative broker because either:
 * Using "structured", and the Content-Type should reflect it (no way to set Content-Type)
 * Using "binary" and the Content-Type should be extracted from `dataContentType` in the returned cloud event.


When there is no error I'm currently using this to properly return a CloudEvent:
```
      res.set(HTTPEmitter.headers(result))
      res.status(200).send(JSON.stringify(result.data, null, 2))
```

I think what you want is probably either:
 * `sendCloudEventResponse` that handles CE properly
 * A clause in `sendResponse` to properly handle the semantics when the return type (or `callback` arg) is a `CloudEvent`.

**Comment by grant** [comment] 2020-11-10 01:24
Hi, Thanks for the details. It would really help to have a full set of reproduction steps within this issue, so I can follow them.

I'll create some that I think you're using here:

```sh
npm init
npm i @google-cloud/functions-framework cloudevents
```

Create `index.js`:

```js
const { CloudEvent, HTTP } = require('cloudevents');

function event(req, res) {
  const receivedEvent = HTTP.toEvent({
    headers: req.headers,
    body: req.body
  });
  console.log(receivedEvent.id);

  const respondEvent = new CloudEvent({
    type: 'dev.mink.apply.samples.divide',
    source: 'https://github.com/mattmoor/mink-apply-sample/divide',
    time: new Date(),
    dataContentType: 'application/json',
    data: { foo: 'bar' }
  }, false);
  res.send(respondEvent);
}

exports.event = event;
```

Create `project.toml`:

```toml
[[build.env]]
name = "GOOGLE_FUNCTION_TARGET"
value = "event"
```

Run:

```
pack build --builder=gcr.io/buildpacks/builder sample-functions-framework-node
docker run -it -ePORT=8080 -p8080:8080 sample-functions-framework-node
```

Test:

```
curl -X POST \
-H 'Content-Type: application/json' \
-H 'ce-type: foo' \
-H 'ce-specversion: 1.0' \
-H 'ce-source: blah' \
-H 'ce-id: 1234' \
-d '{"a": 3, "b": 4}' localhost:8080
```

```
{"id":"2ed8d2e7-2fb3-4a91-bd8e-5a35d2f607f9","type":"dev.mink.apply.samples.divide","source":"https://github.com/mattmoor/mink-apply-sample/divide","specversion":"1.0","dataContentType":"application/json","time":"2020-11-10T01:11:23.570Z","data":{"foo":"bar"}}
```

---

I got this working without issue. You need to use a normal HTTP signature so you can customize your response, but I cannot reproduce the issue. Making clear EXPECTED / ACTUAL behavior in the first comment would help me understand what you want changed in the Functions Framework.

**Comment by mattmoor** [comment] 2020-11-10 02:58
I called out the issue in my first post:

> In the above the `Content-Type` header in the response should be `application/cloudevent+json`

Your repro (like my original post) has `Content-Type: application/json`.


@grantr @harwayne Can one of y'all help @grant here?

**Comment by grant** [comment] 2020-11-10 03:59
Sorry, I don't follow the core issue. There are many assumptions and the original post doesn't have complete repro steps (i.e. how did you start the functions framework?)

- `application/cloudevent+json` is not a valid MIME type. So I would not expect this library to use that type. https://github.com/cloudevents/spec/issues/557
  - If you did want to use this MIME type, you can send whatever `Content-Type` we'd like with something like `res.set('Content-Type', 'application/cloudevent+json')` in your function.

What other issue is there?

**Comment by mattmoor** [comment] 2020-11-10 04:44
This MIME type is what literally every single CloudEvent SDK is expecting for "structured" CloudEvents:

* js: https://github.com/cloudevents/sdk-javascript/blob/14468980f7a79da836bd3ee8304a8a5710a206c1/src/constants.ts#L13
* go: https://github.com/cloudevents/sdk-go/blob/0a5202bf31a5927f261fb8ee0bba88cef0963d8c/v2/event/content_type.go#L8
* java: https://github.com/cloudevents/sdk-java/blob/de2052c4d698366045b0599f4263a55b27443499/formats/json-jackson/src/main/java/io/cloudevents/jackson/JsonFormat.java#L38
* rust: https://github.com/cloudevents/sdk-rust/blob/2b91ee8d7aa30282c7827463540ba7508bfc764a/cloudevents-sdk-reqwest/src/headers.rs#L59
* python: https://github.com/cloudevents/sdk-python/blob/8773319279339b48ebfb7b856b722a2180458f5f/cloudevents/sdk/converters/structured.py#L27
* ruby: https://github.com/cloudevents/sdk-ruby/blob/879aa3c789184e42fbac4c72def3466194b94c1e/lib/cloud_events/http_binding.rb#L103-L105
* csharp: https://github.com/cloudevents/sdk-csharp/blob/248e4f4267ce3ca5c725824fce8592aa7f7808d2/src/CloudNative.CloudEvents.AspNetCore/CloudEventJsonInputFormatter.cs#L18

However, as I said above there's another alternative:

> OR it should return the body:
> ...
> ... and return the remaining headers via their respective `ce-`prefixed equivalents (e.g. `ce-type: dev.mink.apply.samples.divide`).

This form is called "binary" CloudEvents, and it would use the `dataContentType` embedded in the cloud event, and set all of the appropriate `ce-` headers.

---

I don't particularly care which form y'all pick to serialize the return value, but the encoding being used today is not a valid encoding of a CloudEvent.  Hopefully @grantr and @harwayne can help you further.

**Comment by mattmoor** [comment] 2020-11-12 15:09
Here's a unit test showing the Go SDK accepting a structured cloud event as input using this same MIME type.
https://github.com/GoogleCloudPlatform/functions-framework-go/blob/fed357741a8521eeeaad9b32dc140d69ea69626c/funcframework/framework_test.go#L244-L258

Here you don't use the SDK, and this logic might actually be incorrect 🤔 
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/2449956aeef7db4a33e89760ab97ce4a892ff03c/src/invoker.ts#L145-L146

**Comment by mattmoor** [comment] 2020-11-12 15:32
Sounds like this is inconsistent with what all of the existing SDKs do ([slack thread](https://knative.slack.com/archives/C9JP909F0/p1605193801238600))

> the algorithm we use to distinguish is roughly the same across all the sdks:
> ```
> if content-type != null and matches one of the supported event formats {
>   structured
> } else if ce-specversion header is there with a known value {
>   binary
> } else {
>  unknown
> }
> ```

**Comment by grant** [comment] 2021-02-03 18:08
Again, thanks for filing the issue.

This module doesn't send CloudEvents (nor does other FFs). Replies to event-driven functions are not used. As a result, I'm going to close this issue.

There are a lot of comments here and it's not clear what the expected concrete change or behavior should be and why workarounds don't work.

If you'd like to support a feature like this, a clear expected behavior, with **step-by-step instructions** of how to reproduce the issue would help. A PR would help as well.

**Closed by grant** 2021-02-03 18:08 UTC
