### ISSUE TITLE
Best way to deploy TypeScript function to Cloud Function?

### ISSUE THREAD

**Issue by dmiranda2791** [GoogleCloudPlatform/functions-framework-nodejs#254] opened 2021-02-05 16:38 UTC
I am using the TypeScript template to write the function and I faced some issues trying to deploy it using the gcloud functions deploy command.

I tried: 

* The intuitive commando: 

```
gcloud functions deploy pocReadFromBigQueryWriteToFirestore \
--runtime nodejs10 --trigger-http --allow-unauthenticated
```

Got the error 

```
Deploying function (may take a while - up to 2 minutes)...failed.                                        
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: index.js does not exist; Error ID: e1b2ac36
```

* Then, passing a source argument pointing to the build/src directory. 
```
gcloud functions deploy pocReadFromBigQueryWriteToFirestore \
--source=build/src \
--runtime nodejs12 --trigger-http --allow-unauthenticated
```
Got this error in the cli
```
Deploying function (may take a while - up to 2 minutes)...failed.                                        
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Function failed on loading user code. This is likely due to a bug in the user code. Error message: Error: please examine your function logs to see the error cause: https://cloud.google.com/functions/docs/monitoring/logging#viewing_logs. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.
```
And this one on the functions logs:

```
2021-02-04T17:47:55.029ZpocReadFromBigQueryWriteToFirestore Provided module can't be loaded.
Default
2021-02-04T17:47:55.029ZpocReadFromBigQueryWriteToFirestore Did you list all required modules in the package.json dependencies?
```

Next, I tried copying the package.json into the build/src folder and rerun the same command as above.

```
Deploying function (may take a while - up to 2 minutes)...failed.                                        
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: > protobufjs@6.10.2 postinstall /workspace/node_modules/protobufjs
> node scripts/postinstall


> cloud-function-poc@1.0.0 prepare /workspace
> yarn run compile

yarn run v1.22.4
$ tsc
/bin/sh: 1: tsc: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! cloud-function-poc@1.0.0 prepare: `yarn run compile`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the cloud-function-poc@1.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /builder/home/.npm/_logs/2021-02-04T20_07_18_893Z-debug.log; Error ID: beaf8772
```

Finally, I got it working by copying package.json to build/src/package.json and removing the scripts `prepare`, `pretest` and `posttest`. So, I got to think and I wonder:

* Why and how this scripts affect the deployment?
* What is the best strategy to deployment?

Thanks!

**Comment by grant** [comment] 2021-02-05 18:03
Hi, have you looked at other related issues?
- https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/13
- https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/52

There are many different configurations depending on how you like to write TS. In general, first build your TS into JS and then you can test the JS with the Functions Framework locally. That will ensure you don't get errors before you deploy. Make sure your build directory isn't ignored and that things work locally.

**Comment by dmiranda2791** [comment] 2021-02-06 01:32
@grant thanks for pointing those out. I don't have issues with the development workflow in my local but do you know why the deployment fails when the function is deployed with this package.json? The error shows an execution of the `prepare` script but I don't know is executed at deployment.

```
{
  "name": "cloud-function-poc",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "gts lint",
    "clean": "gts clean",
    "compile": "tsc",
    "fix": "gts fix",
    "prepare": "yarn run compile",
    "pretest": "yarn run compile",
    "posttest": "yarn run lint",
    "start": "functions-framework --source=build/src/ --target=pocReadFromBigQueryWriteToFirestore",
    "watch": "concurrently \"tsc -w\" \"nodemon --watch ./build/ --exec npm run start\""
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@google-cloud/bigquery": "^5.5.0",
    "@google-cloud/firestore": "^4.9.1",
    "@google-cloud/functions-framework": "^1.7.1",
    "eslint": "^7.2.0",
    "eslint-config-prettier": "^7.2.0"
  },
  "devDependencies": {
    "@types/express": "^4.17.11",
    "@types/node": "^14.11.2",
    "concurrently": "^5.3.0",
    "eslint-plugin-import": "^2.22.1",
    "gts": "^3.1.0",
    "nodemon": "^2.0.7",
    "typescript": "^4.0.3"
  }
}

```

**Comment by grant** [comment] 2021-02-06 23:57
Hi,
The issue doesn't look like it's with the Functions Framework.

The main error posted above is:
/bin/sh: 1: tsc: not found

It looks like your function is trying to build the TS program before deploying, so you need typescript to be available. Right now it isn't installed because it's a dev dep. Maybe move it to a dep or be sure to run tsc before deploying to Cloud Functions.

**Comment by dmiranda2791** [comment] 2021-02-08 19:13
Hey @grant, the thing is that I want to deploy the files that have already been built by TypeScript, which are in `build/src`, but when the function is being deployed it runs the `prepare` scripts by its self.

**Comment by grant** [comment] 2021-02-08 19:18
@dmiranda2791 OK. Prebuilt JS files are great.

This seems like an issue with the function code.

In order for me to triage this issue, I need a minimal sample, full steps from start to finish of how you're deploying to GCF.

I don't know why `index.js does not exist; Error ID: e1b2ac36`. Maybe you're ignoring the build directory on accident when uploading to GCF.

Either way, this isn't a Functions Framework issue, unless you see something I'm missing.

**Comment by grant** [comment] 2021-02-08 19:45
I'm going to close this as the identified error does not pertain to the Functions Framework, rather it is user code. But feel free to keep commenting. As mentioned, clear reproduction steps would help.

I've provided a bunch of tips and possible errors in the code in comments above.

**Closed by grant** 2021-02-08 19:45 UTC

**Comment by MoSattler** [comment] 2021-03-31 14:54
I got a similar problem. When generating a project as described [here](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/docs/typescript.md), and then trying to deploy the function with
```bash
gcloud functions deploy helloWorld --runtime nodejs10 --trigger-http
```
I do get
```
build/src/index.js does not exist
```

**Comment by ash67** [comment] 2021-04-28 04:25
@grant I am having exactly the same issue as @dmiranda2791.

so when GTS complies typescript code into js and places the compiled JS code into the `build/src` folder. However, it does not copy package.json over to the `build/src` folder. So the possible solution is to manually copy the package.json file and remove `prepare, pretest and posttest` scripts.

so when deploying a function from the `build/src` folder, it works just fine.

I would like to ask if there was a better approach than this? Ideally the `build/src` should have compiled JS code with package.json file so the whole folder can be deployed.

**Comment by grant** [comment] 2021-04-28 04:29
> @grant I am having exactly the same issue as @dmiranda2791.
> 
> so when GTS complies typescript code into js and places the compiled JS code into the `build/src` folder. However, it does not copy package.json over to the `build/src` folder. So the possible solution is to manually copy the package.json file and remove `prepare, pretest and posttest` scripts.
> 
> so when deploying a function from the `build/src` folder, it works just fine.
> 
> I would like to ask if there was a better approach than this? Ideally the `build/src` should have compiled JS code with package.json file so the whole folder can be deployed.

Can you provide the list of steps to repro?

Would something like this in the `package.json` help?:

```
  "scripts": {
    "start": "functions-framework --source=build/src"
  }
```

**Comment by ash67** [comment] 2021-04-28 04:49
@grant thanks for the prompt response!

Here are the steps:

1. I followed the steps mentioned [here](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/docs/typescript.md) to create a project, write code in TS, run & test code locally.
2. My project had dependencies of other NPM modules so I added them in the package.json file
3. GTS created the `build/src` folder which contained the complied JS code without package.json file.
4. I deployed my function code from the `build/src` folder

Of course, it did not work because the `build/src` folder didn't contain the package.json which listed all my project dependencies. 

The `start` script you suggested is already in my project and it works fine locally. It serves my function code at localhost:8080.

So should I deploy the pre-compiled code that is inside the `build/src` directory or deploy the TS code that would be compiled into JS when the function is being deployed?

**Comment by grant** [comment] 2021-04-28 05:27
Thanks!

Yes, I see how something is broken in this flow. So I followed those steps, skipping the nodemon part. I then ran the FF locally - that worked.

Then I deployed:

```
gcloud functions deploy ash67 --runtime nodejs12 --trigger-http --allow-unauthenticated
```

And got the error:

```
Deploying function (may take a while - up to 2 minutes)...failed.                        
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: > @0.0.0 prepare /workspace
> npm run compile


> @0.0.0 compile /workspace
> tsc

sh: 1: tsc: not found
```

It looks like the gts init script compiles in prod, we probably don't want that because we don't want to install TS when building, let's build locally.

Remove line:

```
"prepare": "npm run compile",
```

Deploy:

```
gcloud functions deploy ash67 --runtime nodejs12 --trigger-http --allow-unauthenticated --entry-point helloWorld
```

There's a different error for not finding the function in the root dir. For a workaround, I created a `index.js` file in the root directory with this:

```
exports.helloWorld = require('./build/src/index').helloWorld;
```

Seems to work. Just remember to build/watch before deploying.

https://us-central1-test-grant.cloudfunctions.net/ash67

I'm not sure why configuring a source in the npm start FF script isn't working in prod, only locally. But this workaround seems pretty lightweight.

Hope that helps.

**Comment by ash67** [comment] 2021-04-28 07:04
@grant 

Thanks so much for providing this workaround. It works like a charm.

**Comment by johnnyoshika** [comment] 2021-05-17 16:53
This is very interesting. I had the exact same problem as the OP, but as soon as I removed `"prepare": "npm run compile"` from package.json, deployment worked.

**Comment by mcorcuera** [comment] 2021-06-10 07:00
I was having the same issue where my TS compiled field where under `build/`, but I was getting the error:

`ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: index.js does not exist; Error ID: e1b2ac36`

I found out that the `gcloud functions deploy` command will take into account the file configured as `main` in the `package.json`. So having a configuration like this will make it work:

```json
{
  "name": "cloud_functions_typescript",
  "version": "1.0.0",
  "description": "Cloud functions typescript",
  "main": "build/index.js",
  "scripts": { ...}
}
```

**Comment by hammadzz** [comment] 2021-06-12 12:25
I hope I am wrong, but there is no way to ship a zip package to Google Cloud Functions as it would solve this issue. But since GCF is intent on installing the npm packages for you it breaks. I don't want GCF doing CI/CD work. It shouldn't be concerned about my dependencies. I want to deploy an artifact that isn't mutated. AWS supports this with a zip upload to AWS Lambda. 

I understand that fixes the issue with native modules compiled that work on your local machine but won't in GCF. Although that is an easy fix in CI/CD by using the right docker image / container to install npm modules inside.

For this reason I opted for Cloud Run instead to overcome this issue. If anyone knows a work around do let us know.

**Comment by johannesgiani** [comment] 2022-01-11 16:51
@grant maybe that workaround could be mentioned in the [typescript docs](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/docs/typescript.md) that @ash67 referred to.

Proposal:
* remove `prepare` script in package.json
* adjust main 
```
"main": "build/src/index.js",
```

**Comment by grant** [comment] 2022-01-11 16:55
@johannesgiani PRs are welcome. The TypeScript doc is a community example doc that I'm sure could be improved / updated. :)

**Comment by toddbaert** [comment] 2022-01-11 20:56
Unless I'm very confused, the configuration of the scripts in the framework is a bit non-nonsensical combined with what runs automatically in Cloud Build.

`npm ci --quiet (NODE_ENV=production)`: does NOT install dev dependencies
`prepare`: runs after install, including `npm ci` as above, and in this case runs `npm run compile`
`compile`: runs `tsc`, which _often requries dev dependencies, and are not present_ because of the aforementioned production ci run.

This is easily observed locally by deleting your node modules and running `npm ci --prodction`. How is this supposed to work? What am I missing?

**Comment by johannesgiani** [comment] 2022-01-12 10:00
@grant sure let me try that, but for some reason I get `remote: Permission to GoogleCloudPlatform/functions-framework-nodejs.git denied to johannesgiani` when pushing my branch (using username and access token for public repo). I setup the open source agreement following the contributing docs. Anything else to setup?

@toddbaert did you try just removing the `prepare` script that was generated by `gts`?

**Comment by grant** [comment] 2022-01-12 10:41
> @grant sure let me try that, but for some reason I get `remote: Permission to GoogleCloudPlatform/functions-framework-nodejs.git denied to johannesgiani` when pushing my branch (using username and access token for public repo). I setup the open source agreement following the contributing docs. Anything else to setup?

Please use a fork and create a PR. I think that error states you've tried to push a branch from a clone, not fork.

**Comment by toddbaert** [comment] 2022-01-12 14:57
@johannesgiani I can certainly remove the script, but I'm trying to make a larger point that the way the scrips are written is fundamentally flawed. A `prepare` step with a tsc in it is a bad idea, because it will always cause errors after a production NPM install assuming people are using devDependencies idiomatically.

**Comment by xav-ie** [comment] 2023-04-27 21:27
> A `prepare` step with a `tsc` in it is a bad idea, because it will always cause errors after a production NPM install assuming people are using devDependencies idiomatically.

Were you ever able to figure this out? @hammadzz
