### ISSUE TITLE
`gcp-build` not executed in node.js 10

### ISSUE THREAD

**Issue by ricbir** [GoogleCloudPlatform/functions-framework-nodejs#111] opened 2019-11-26 17:10 UTC
Hi
I have been trying to use the `gcp-build` feature [documented here](https://cloud.google.com/functions/docs/writing/specifying-dependencies-nodejs#executing_custom_build_steps_during_deployment), but it only seems to work in node.js 8.
When I use node.js 10 the step is skipped entirely.

Any help you can provide would be very much appreciated

**Comment by hdp617** [comment] 2019-11-26 17:27
Thanks for reporting this issue. Could you provide reproducible steps?

**Comment by ricbir** [comment] 2019-11-27 16:14
Sure.

Create a directory with the following files:

**package.json**
```JSON
{
    "scripts": {
        "gcp-build": "tsc index.ts"
    },
    "dependencies": {
        "@google-cloud/functions-framework": "1.3.2"
    },
    "devDependencies": {
        "typescript": "^3.7.2"
    }
}
```

**index.ts**
```TypeScript
export const helloWorld = (req, res) => {
    let message = req.query.message || req.body.message || 'Hello World!';
    res.status(200).send(message);
  };
```

If you run 
```
gcloud functions deploy --runtime=nodejs8 --region=europe-west2 --trigger-http --entry-point=helloWorld test-function
```
The function deploys succesfully, as `gcp-build` is run and `index.ts` is compiled to `index.js`

If you run
```
gcloud functions deploy --runtime=nodejs10 --region=europe-west2 --trigger-http --entry-point=helloWorld test-function
```
The deployment times out, and in the logs it reads:
```
Provided code is not a loadable module.
```

**Comment by hdp617** [comment] 2019-12-03 18:37
Thanks for the reproducible steps. This is a bug with GCF. I'll make sure this is fixed before GA.

**Comment by hdp617** [comment] 2019-12-19 18:11
Closed since this is not a Functions Framework bug. I'll give an update when the fix is in GCF.

**Closed by hdp617** 2019-12-19 18:11 UTC
Labels: bug

**Comment by chrisfischer** [comment] 2020-05-07 04:38
Any update on this?

**Comment by hdp617** [comment] 2020-05-07 04:41
This issue should be fixed now.

**Comment by killthekitten** [comment] 2020-06-19 18:37
@hdp617 I'm getting the same issue locally by copying @ricbir's code and running:

```bash
yarn install
node --inspect node_modules/@google-cloud/functions-framework --target=helloWorld
```

**Comment by hdp617** [comment] 2020-06-19 19:21
`yarn install` doesn't run the `gcp-build` script so you'd have to do
```
yarn install
yarn run gcp-build
node --inspect node_modules/@google-cloud/functions-framework --target=helloWorld
```

If you want `yarn install` to run `gcp-build` script, you can add a `prepare` script [0]. For example, in `package.json`,
```
"scripts": {
    "prepare": "yarn run gcp-build",
    "gcp-build": "tsc -p ."
 }
```

[0] https://classic.yarnpkg.com/en/docs/package-json/#toc-scripts

**Comment by killthekitten** [comment] 2020-06-19 20:13
@hdp617 thanks for clarification. I was under impression that the framework is aware of `gcp-build` script and should somehow pick it up. I can see now there are no mentions of it in the codebase.

**Comment by hdp617** [comment] 2020-06-19 20:25
The framework just loads a function and sets up a web server to invoke the function. If you're interested, the `gcp-build` script is handled [here](https://github.com/GoogleCloudPlatform/buildpacks/blob/master/cmd/nodejs/yarn_gcp_build/main.go).

**Comment by killthekitten** [comment] 2020-06-19 20:38
@hdp617 that's it, thanks!
